In [1]:
import pandas as pd

In [2]:
data1 = pd.read_csv("C:/Users/katik/Downloads/CSV/CSV/Aqueduct40_future_annual_y2023m07d05.csv")
#Setting options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Print the full list of columns
print(data1.columns.tolist())

['fid', 'pfaf_id', 'bau30_ba_x_r', 'bau30_ba_x_l', 'bau50_ba_x_r', 'bau50_ba_x_l', 'bau80_ba_x_r', 'bau80_ba_x_l', 'opt30_ba_x_r', 'opt30_ba_x_l', 'opt50_ba_x_r', 'opt50_ba_x_l', 'opt80_ba_x_r', 'opt80_ba_x_l', 'pes30_ba_x_r', 'pes30_ba_x_l', 'pes50_ba_x_r', 'pes50_ba_x_l', 'pes80_ba_x_r', 'pes80_ba_x_l', 'bau30_ww_x_r', 'bau30_ww_x_l', 'bau50_ww_x_r', 'bau50_ww_x_l', 'bau80_ww_x_r', 'bau80_ww_x_l', 'opt30_ww_x_r', 'opt30_ww_x_l', 'opt50_ww_x_r', 'opt50_ww_x_l', 'opt80_ww_x_r', 'opt80_ww_x_l', 'pes30_ww_x_r', 'pes30_ww_x_l', 'pes50_ww_x_r', 'pes50_ww_x_l', 'pes80_ww_x_r', 'pes80_ww_x_l', 'bau30_ws_x_r', 'bau30_ws_x_s', 'bau30_ws_x_c', 'bau30_ws_x_l', 'bau50_ws_x_r', 'bau50_ws_x_s', 'bau50_ws_x_c', 'bau50_ws_x_l', 'bau80_ws_x_r', 'bau80_ws_x_s', 'bau80_ws_x_c', 'bau80_ws_x_l', 'opt30_ws_x_r', 'opt30_ws_x_s', 'opt30_ws_x_c', 'opt30_ws_x_l', 'opt50_ws_x_r', 'opt50_ws_x_s', 'opt50_ws_x_c', 'opt50_ws_x_l', 'opt80_ws_x_r', 'opt80_ws_x_s', 'opt80_ws_x_c', 'opt80_ws_x_l', 'pes30_ws_x_r', 'pes30_ws_x_s', 'pes30_ws_x_c', 'pes30_ws_x_l', 'pes50_ws_x_r', 'pes50_ws_x_s', 'pes50_ws_x_c', 'pes50_ws_x_l', 'pes80_ws_x_r', 'pes80_ws_x_s', 'pes80_ws_x_c', 'pes80_ws_x_l', 'bau30_wd_x_r', 'bau30_wd_x_s', 'bau30_wd_x_c', 'bau30_wd_x_l', 'bau50_wd_x_r', 'bau50_wd_x_s', 'bau50_wd_x_c', 'bau50_wd_x_l', 'bau80_wd_x_r', 'bau80_wd_x_s', 'bau80_wd_x_c', 'bau80_wd_x_l', 'opt30_wd_x_r', 'opt30_wd_x_s', 'opt30_wd_x_c', 'opt30_wd_x_l', 'opt50_wd_x_r', 'opt50_wd_x_s', 'opt50_wd_x_c', 'opt50_wd_x_l', 'opt80_wd_x_r', 'opt80_wd_x_s', 'opt80_wd_x_c', 'opt80_wd_x_l', 'pes30_wd_x_r', 'pes30_wd_x_s', 'pes30_wd_x_c', 'pes30_wd_x_l', 'pes50_wd_x_r', 'pes50_wd_x_s', 'pes50_wd_x_c', 'pes50_wd_x_l', 'pes80_wd_x_r', 'pes80_wd_x_s', 'pes80_wd_x_c', 'pes80_wd_x_l', 'bau30_iv_x_r', 'bau30_iv_x_s', 'bau30_iv_x_c', 'bau30_iv_x_l', 'bau50_iv_x_r', 'bau50_iv_x_s', 'bau50_iv_x_c', 'bau50_iv_x_l', 'bau80_iv_x_r', 'bau80_iv_x_s', 'bau80_iv_x_c', 'bau80_iv_x_l', 'opt30_iv_x_r', 'opt30_iv_x_s', 'opt30_iv_x_c', 'opt30_iv_x_l', 'opt50_iv_x_r', 'opt50_iv_x_s', 'opt50_iv_x_c', 'opt50_iv_x_l', 'opt80_iv_x_r', 'opt80_iv_x_s', 'opt80_iv_x_c', 'opt80_iv_x_l', 'pes30_iv_x_r', 'pes30_iv_x_s', 'pes30_iv_x_c', 'pes30_iv_x_l', 'pes50_iv_x_r', 'pes50_iv_x_s', 'pes50_iv_x_c', 'pes50_iv_x_l', 'pes80_iv_x_r', 'pes80_iv_x_s', 'pes80_iv_x_c', 'pes80_iv_x_l', 'bau30_sv_x_r', 'bau30_sv_x_s', 'bau30_sv_x_c', 'bau30_sv_x_l', 'bau50_sv_x_r', 'bau50_sv_x_s', 'bau50_sv_x_c', 'bau50_sv_x_l', 'bau80_sv_x_r', 'bau80_sv_x_s', 'bau80_sv_x_c', 'bau80_sv_x_l', 'opt30_sv_x_r', 'opt30_sv_x_s', 'opt30_sv_x_c', 'opt30_sv_x_l', 'opt50_sv_x_r', 'opt50_sv_x_s', 'opt50_sv_x_c', 'opt50_sv_x_l', 'opt80_sv_x_r', 'opt80_sv_x_s', 'opt80_sv_x_c', 'opt80_sv_x_l', 'pes30_sv_x_r', 'pes30_sv_x_s', 'pes30_sv_x_c', 'pes30_sv_x_l', 'pes50_sv_x_r', 'pes50_sv_x_s', 'pes50_sv_x_c', 'pes50_sv_x_l', 'pes80_sv_x_r', 'pes80_sv_x_s', 'pes80_sv_x_c', 'pes80_sv_x_l']

In [3]:
import pandas as pd
import re
data1 = pd.read_csv("C:/Users/katik/Downloads/CSV/CSV/Aqueduct40_future_annual_y2023m07d05.csv")




# Define mapping dictionaries and parser function
scenario_map = {
    "bau": "Business as Usual",
    "opt": "Optimistic",
    "pes": "Pessimistic"
}
year_map = {
    "30": "2030 (2015-2045)",
    "50": "2050 (2035-2065)",
    "80": "2080 (2065-2095)"
}
var_map = {
    "ba": "Blue Water Availability",
    "ww": "Withdrawals",
    "ws": "Water Stress",
    "wd": "Water Depletion",
    "iv": "Interannual Variability",
    "sv": "Seasonal Variability"
}
type_map = {
    "r": "Raw Value (Median of 5 GCMs)",
    "s": "Score [0-5 scale]",
    "l": "Label (Threshold Explanation)",
    "c": "Category (Integer for Visuals)"
}

def get_full_col(col):
    if col in ["fid", "pfaf_id"]:
        return {"fid": "Feature ID", "pfaf_id": "Pfafstetter ID"}[col]
    match = re.match(r'(bau|opt|pes)(30|50|80)_([a-z]{2})_x_([rslc])', col)
    if match:
        scenario, year, var, ctype = match.groups()
        scenario_full = scenario_map.get(scenario, scenario)
        year_full = year_map.get(year, year)
        var_full = var_map.get(var, var)
        type_full = type_map.get(ctype, ctype)
        return f"{var_full} ({scenario_full}, Year {year_full}) - {type_full}"
    return col

# Build column conversion dict
col_fullforms = {col: get_full_col(col) for col in data1.columns}

# Rename columns
data1.rename(columns=col_fullforms, inplace=True)

# Save to CSV
data1.to_csv("Aqueduct_future.csv", index=False)

In [4]:
data1.head(10)

,Feature ID,Pfafstetter ID,"Blue Water Availability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Blue Water Availability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Blue Water Availability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Blue Water Availability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Blue Water Availability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Blue Water Availability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Blue Water Availability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Blue Water Availability (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Blue Water Availability (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Blue Water Availability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Withdrawals (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Withdrawals (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Withdrawals (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Withdrawals (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Withdrawals (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Withdrawals (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Withdrawals (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Withdrawals (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Withdrawals (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Withdrawals (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Withdrawals (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Withdrawals (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Withdrawals (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Withdrawals (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Withdrawals (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Withdrawals (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Withdrawals (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Withdrawals (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Water Stress (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Water Stress (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]","Water Stress (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Water Stress (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Water Stress (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Water Stress (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]","Water Stress (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Water Stress (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Water Stress (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Water Stress (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]","Water Stress (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Water Stress (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Water Stress (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Water Stress (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Water Stress (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Water Stress (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Water Stress (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Water Stress (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Water Stress (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Water Stress (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Water Stress (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Water Stress (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Water Stress (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Water Stress (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Water Stress (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Water Stress (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Water Stress (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Water Stress (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Water Stress (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Water Stress (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Water Stress (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Water Stress (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Water Stress (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Water Stress (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Water Stress (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Water Stress (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]","Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]","Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]","Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Water Depletion (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Water Depletion (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Water Depletion (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Water Depletion (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Water Depletion (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Water Depletion (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Water Depletion (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Water Depletion (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Water Depletion (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Water Depletion (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Water Depletion (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Water Depletion (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]","Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]","Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]","Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]","Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]","Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]","Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)","Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]","Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)","Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)","Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]","Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)","Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)","Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)","Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]","Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)","Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)"
0,1,811101,215.566367,100-300 cm,221.042707,100-300 cm,233.179081,100-300 cm,221.999608,100-300 cm,228.321120,100-300 cm,237.270088,100-300 cm,222.814075,100-300 cm,230.686944,100-300 cm,246.831698,100-300 cm,7.155680e-04,< 1 cm,7.155740e-04,< 1 cm,7.155620e-04,< 1 cm,7.155680e-04,< 1 cm,7.155740e-04,< 1 cm,7.155620e-04,< 1 cm,7.155680e-04,< 1 cm,7.155740e-04,< 1 cm,7.155620e-04,< 1 cm,3.350000e-06,0.0,0.0,Low (<10%),3.260000e-06,0.0,0.0,Low (<10%),3.100000e-06,0.0,0.0,Low (<10%),3.240000e-06,0.0,0.0,Low (<10%),3.150000e-06,0.0,0.0,Low (<10%),3.050000e-06,0.0,0.0,Low (<10%),3.230000e-06,0.0,0.0,Low (<10%),3.150000e-06,0.0,0.0,Low (<10%),2.960000e-06,0.0,0.0,Low (<10%),3.350000e-06,6.690000e-05,0.0,Low (<5%),3.260000e-06,6.510000e-05,0.0,Low (<5%),3.100000e-06,6.200000e-05,0.0,Low (<5%),3.240000e-06,6.490000e-05,0.0,Low (<5%),3.150000e-06,6.300000e-05,0.0,Low (<5%),3.050000e-06,6.100000e-05,0.0,Low (<5%),3.230000e-06,6.460000e-05,0.0,Low (<5%),3.150000e-06,6.290000e-05,0.0,Low (<5%),2.960000e-06,5.910000e-05,0.0,Low (<5%),0.133550,0.534199,0.0,Low (<0.25),0.125308,0.501233,0.0,Low (<0.25),0.129470,0.517880,0.0,Low (<0.25),0.127594,0.510375,0.0,Low (<0.25),0.115402,0.461609,0.0,Low (<0.25),0.117101,0.468402,0.0,Low (<0.25),0.125755,0.503019,0.0,Low (<0.25),0.112950,0.451801,0.0,Low (<0.25),0.127261,0.509043,0.0,Low (<0.25),0.064091,0.192273,0.0,Low (<0.33),0.064474,0.193421,0.0,Low (<0.33),0.080796,0.242388,0.0,Low (<0.33),0.057891,0.173672,0.0,Low (<0.33),0.062342,0.187026,0.0,Low (<0.33),0.061770,0.185309,0.0,Low (<0.33),0.057720,0.173160,0.0,Low (<0.33),0.064235,0.192705,0.0,Low (<0.33),0.078885,0.236654,0.0,Low (<0.33)
1,2,811102,176.412318,100-300 cm,181.376294,100-300 cm,200.294791,100-300 cm,184.740674,100-300 cm,188.708792,100-300 cm,201.595278,100-300 cm,182.504287,100-300 cm,189.899271,100-300 cm,211.796788,100-300 cm,2.325919e-02,< 1 cm,2.325583e-02,< 1 cm,2.092398e-02,< 1 cm,2.440480e-02,< 1 cm,2.875855e-02,< 1 cm,3.388324e-02,< 1 cm,2.465296e-02,< 1 cm,2.986071e-02,< 1 cm,3.659876e-02,< 1 cm,1.538530e-04,0.0,0.0,Low (<10%),1.398940e-04,0.0,0.0,Low (<10%),1.121420e-04,0.0,0.0,Low (<10%),1.517480e-04,0.0,0.0,Low (<10%),1.671230e-04,0.0,0.0,Low (<10%),1.832850e-04,0.0,0.0,Low (<10%),1.489760e-04,0.0,0.0,Low (<10%),1.707780e-04,0.0,0.0,Low (<10%),1.960400e-04,0.0,0.0,Low (<10%),3.310000e-05,6.624130e-04,0.0,Low (<5%),2.880000e-05,5.757160e-04,0.0,Low (<5%),2.170000e-05,4.340550e-04,0.0,Low (<5%),3.360000e-05,6.717230e-04,0.0,Low (<5%),3.880000e-05,7.757490e-04,0.0,Low (<5%),4.550000e-05,9.092540e-04,0.0,Low (<5%),3.410000e-05,6.813400e-04,0.0,Low (<5%),4.470000e-05,8.942880e-04,0.0,Low (<5%),5.970000e-05,1.194447e-03,0.0,Low (<5%),0.259137,1.036548,1.0,Low - Medium (0.25-0.50),0.239330,0.957321,0.0,Low (<0.25),0.237688,0.950754,0.0,Low (<0.25),0.219463,0.877854,0.0,Low (<0.25),0.219863,0.879451,0.0,Low (<0.25),0.215138,0.860551,0.0,Low (<0.25),0.228585,0.914338,0.0,Low (<0.25),0.223321,0.893283,0.0,Low (<0.25),0.223308,0.893232,0.0,Low (<0.25),0.387419,1.162258,1.0,Low - Medium (0.33-0.66),0.309155,0.927464,0.0,Low (<0.33),0.226016,0.678047,0.0,Low (<0.33),0.357578,1.072733,1.0,Low - Medium (0.33-0.66),0.328029,0.984088,0.0,Low (<0.33),0.351866,1.055598,1.0,Low - Medium (0.33-0.66),0.363313,1.089938,1.0,Low - Medium (0.33-0.66),0.292881,0.878644,0.0,Low (<0.33),0.248830,0.746489,0.0,Low (<0.33)

In [6]:

# Basic column summary:
print("--- Column Names ---")
print(data1.columns.tolist())

print("\n--- Data Types and Nulls ---")
print(data1.info())

print("\n--- First 3 Rows (Quick Preview) ---")
print(data1.head(3))

print("\n--- Numeric/Categorical Stats (Optional) ---")
print(data1.describe(include='all').T)

--- Column Names ---
['Feature ID', 'Pfafstetter ID', 'Blue Water Availability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Blue Water Availability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Blue Water Availability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Blue Water Availability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Blue Water Availability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Blue Water Availability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Blue Water Availability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Blue Water Availability (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Blue Water Availability (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Blue Water Availability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Withdrawals (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Withdrawals (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Withdrawals (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Withdrawals (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Withdrawals (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Withdrawals (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Withdrawals (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Withdrawals (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Withdrawals (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Withdrawals (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Water Stress (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Water Stress (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Water Stress (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Water Stress (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Water Stress (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Water Stress (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Water Stress (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Water Stress (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Water Stress (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Water Stress (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Water Stress (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Water Stress (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Water Stress (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Water Stress (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Water Stress (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Water Stress (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Water Stress (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Water Stress (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Water Stress (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Water Stress (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Water Stress (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Water Stress (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Water Stress (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Water Stress (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Water Stress (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Water Stress (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Water Stress (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Water Stress (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Water Depletion (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Water Depletion (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Water Depletion (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Water Depletion (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Water Depletion (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Water Depletion (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Water Depletion (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Water Depletion (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Water Depletion (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Water Depletion (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Water Depletion (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Water Depletion (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Water Depletion (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Water Depletion (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Water Depletion (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Interannual Variability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Interannual Variability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Interannual Variability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Interannual Variability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Interannual Variability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Interannual Variability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Interannual Variability (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Interannual Variability (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Interannual Variability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Seasonal Variability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Seasonal Variability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Seasonal Variability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Seasonal Variability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Seasonal Variability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Seasonal Variability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)', 'Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Score [0-5 scale]', 'Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Category (Integer for Visuals)', 'Seasonal Variability (Pessimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)', 'Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Score [0-5 scale]', 'Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Category (Integer for Visuals)', 'Seasonal Variability (Pessimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)', 'Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)', 'Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Score [0-5 scale]', 'Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Category (Integer for Visuals)', 'Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)']

--- Data Types and Nulls ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16395 entries, 0 to 16394
Columns: 182 entries, Feature ID to Seasonal Variability (Pessimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)
dtypes: float64(126), int64(2), object(54)
memory usage: 22.8+ MB
None

--- First 3 Rows (Quick Preview) ---
   Feature ID  Pfafstetter ID  \
0           1          811101
1           2          811102
2           3          811103

   Blue Water Availability (Business as Usual, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)  \
0                                         215.566367
1                                         176.412318
2                                         300.085833

  Blue Water Availability (Business as Usual, Year 2030 (2015-2045)) - Label (Threshold Explanation)  \
0                                         100-300 cm
1                                         100-300 cm
2                                        300-1000 cm

   Blue Water Availability (Business as Usual, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)  \
0                                         221.042707
1                                         181.376294
2                                         293.508701

  Blue Water Availability (Business as Usual, Year 2050 (2035-2065)) - Label (Threshold Explanation)  \
0                                         100-300 cm
1                                         100-300 cm
2                                         100-300 cm

   Blue Water Availability (Business as Usual, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)  \
0                                         233.179081
1                                         200.294791
2                                         326.663906

  Blue Water Availability (Business as Usual, Year 2080 (2065-2095)) - Label (Threshold Explanation)  \
0                                         100-300 cm
1                                         100-300 cm
2                                        300-1000 cm

   Blue Water Availability (Optimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)  \
0                                         221.999608
1                                         184.740674
2                                         302.083509

  Blue Water Availability (Optimistic, Year 2030 (2015-2045)) - Label (Threshold Explanation)  \
0                                         100-300 cm
1                                         100-300 cm
2                                        300-1000 cm

   Blue Water Availability (Optimistic, Year 2050 (2035-2065)) - Raw Value (Median of 5 GCMs)  \
0                                         228.321120
1                                         188.708792
2                                         316.936561

  Blue Water Availability (Optimistic, Year 2050 (2035-2065)) - Label (Threshold Explanation)  \
0                                         100-300 cm
1                                         100-300 cm
2                                        300-1000 cm

   Blue Water Availability (Optimistic, Year 2080 (2065-2095)) - Raw Value (Median of 5 GCMs)  \
0                                         237.270088
1                                         201.595278
2                                         316.209828

  Blue Water Availability (Optimistic, Year 2080 (2065-2095)) - Label (Threshold Explanation)  \
0                                         100-300 cm
1                                         100-300 cm
2                                        300-1000 cm

   Blue Water Availability (Pessimistic, Year 2030 (2015-2045)) - Raw Value (Median of 5 GCMs)  \
0                                         222.814075
1                                         182.504287

In [9]:
#Clean & Standardize Column Names
import re
data1.columns = [
    re.sub(r'[^A-Z0-9_]', '_', col.upper().replace(' ', '_'))
    for col in data1.columns
]

In [17]:
data1.head(10)

,FEATURE_ID,PFAFSTETTER_ID,BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____LABEL__THRESHOLD_EXPLANATION_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____RAW_VALUE__MEDIAN_OF_5_GCMS_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____SCORE__0_5_SCALE_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____CATEGORY__INTEGER_FOR_VISUALS_,SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2065_2095_____LABEL__THRESHOLD_EXPLANATION_
0,1,811101,215.566367,100-300 cm,221.042707,100-300 cm,233.179081,100-300 cm,221.999608,100-300 cm,228.321120,100-300 cm,237.270088,100-300 cm,222.814075,100-300 cm,230.686944,100-300 cm,246.831698,100-300 cm,7.155680e-04,< 1 cm,7.155740e-04,< 1 cm,7.155620e-04,< 1 cm,7.155680e-04,< 1 cm,7.155740e-04,< 1 cm,7.155620e-04,< 1 cm,7.155680e-04,< 1 cm,7.155740e-04,< 1 cm,7.155620e-04,< 1 cm,3.350000e-06,0.0,0.0,Low (<10%),3.260000e-06,0.0,0.0,Low (<10%),3.100000e-06,0.0,0.0,Low (<10%),3.240000e-06,0.0,0.0,Low (<10%),3.150000e-06,0.0,0.0,Low (<10%),3.050000e-06,0.0,0.0,Low (<10%),3.230000e-06,0.0,0.0,Low (<10%),3.150000e-06,0.0,0.0,Low (<10%),2.960000e-06,0.0,0.0,Low (<10%),3.350000e-06,6.690000e-05,0.0,Low (<5%),3.260000e-06,6.510000e-05,0.0,Low (<5%),3.100000e-06,6.200000e-05,0.0,Low (<5%),3.240000e-06,6.490000e-05,0.0,Low (<5%),3.150000e-06,6.300000e-05,0.0,Low (<5%),3.050000e-06,6.100000e-05,0.0,Low (<5%),3.230000e-06,6.460000e-05,0.0,Low (<5%),3.150000e-06,6.290000e-05,0.0,Low (<5%),2.960000e-06,5.910000e-05,0.0,Low (<5%),0.133550,0.534199,0.0,Low (<0.25),0.125308,0.501233,0.0,Low (<0.25),0.129470,0.517880,0.0,Low (<0.25),0.127594,0.510375,0.0,Low (<0.25),0.115402,0.461609,0.0,Low (<0.25),0.117101,0.468402,0.0,Low (<0.25),0.125755,0.503019,0.0,Low (<0.25),0.112950,0.451801,0.0,Low (<0.25),0.127261,0.509043,0.0,Low (<0.25),0.064091,0.192273,0.0,Low (<0.33),0.064474,0.193421,0.0,Low (<0.33),0.080796,0.242388,0.0,Low (<0.33),0.057891,0.173672,0.0,Low (<0.33),0.062342,0.187026,0.0,Low (<0.33),0.061770,0.185309,0.0,Low (<0.33),0.057720,0.173160,0.0,Low (<0.33),0.064235,0.192705,0.0,Low (<0.33),0.078885,0.236654,0.0,Low (<0.33)
1,2,811102,176.412318,100-300 cm,181.376294,100-300 cm,200.294791,100-300 cm,184.740674,100-300 cm,188.708792,100-300 cm,201.595278,100-300 cm,182.504287,100-300 cm,189.899271,100-300 cm,211.796788,100-300 cm,2.325919e-02,< 1 cm,2.325583e-02,< 1 cm,2.092398e-02,< 1 cm,2.440480e-02,< 1 cm,2.875855e-02,< 1 cm,3.388324e-02,< 1 cm,2.465296e-02,< 1 cm,2.986071e-02,< 1 cm,3.659876e-02,< 1 cm,1.538530e-04,0.0,0.0,Low (<10%),1.398940e-04,0.0,0.0,Low (<10%),1.121420e-04,0.0,0.0,Low (<10%),1.517480e-04,0.0,0.0,Low (<10%),1.671230e-04,0.0,0.0,Low (<10%),1.832850e-04,0.0,0.0,Low (<10%),1.489760e-04,0.0,0.0,Low (<10%),1.707780e-04,0.0,0.0,Low (<10%),1.960400e-04,0.0,0.0,Low (<10%),3.310000e-05,6.624130e-04,0.0,Low (<5%),2.880000e-05,5.757160e-04,0.0,Low (<5%),2.170000e-05,4.340550e-04,0.0,Low (<5%),3.360000e-05,6.717230e-04,0.0,Low (<5%),3.880000e-05,7.757490e-04,0.0,Low (<5%),4.550000e-05,9.092540e-04,0.0,Low (<5%),3.410000e-05,6.813400e-04,0.0,Low (<5%),4.470000e-05,8.942880e-04,0.0,Low (<5%),5.970000e-05,1.194447e-03,0.0,Low (<5%),0.259137,1.036548,1.0,Low - Medium (0.25-0.50),0.239330,0.957321,0.0,Low (<0.25),0.237688,0.950754,0.0,Low (<0.25),0.219463,0.877854,0.0,Low (<0.25),0.219863,0.879451,0.0,Low (<0.25),0.215138,0.860551,0.0,Low (<0.25),0.228585,0.914338,0.0,Low (<0.25),0.223321,0.893283,0.0,Low (<0.25),0.223308,0.893232,0.0,Low (<0.25),0.387419,1.162258,1.0,Low - Medium (0.33-0.66),0.309155,0.927464,0.0,Low (<0.33),0.226016,0.678047,0.0,Low (<0.33),0.357578,1.072733,1.0,Low - Medium (0.33-0.66),0.328029,0.984088,0.0,Low (<0.33),0.351866,1.055598,1.0,Low - Medium (0.33-0.66),0.363313,1.089938,1.0,Low - Medium (0.33-0.66),0.292881,0.878644,0.0,Low (<0.33),0.248830,0.746489,0.0,Low (<0.33)

In [10]:
#Check Duplicates
print(f"Duplicate rows: {data1.duplicated().sum()}")

Duplicate rows: 0

In [11]:
 #Identify and Replace Fill/Missing Values
import numpy as np
data1.replace([-9999, -9999.0], np.nan, inplace=True)

In [12]:
# Summarize Nulls and Cardinality
# Null counts
print(data1.isnull().sum().sort_values(ascending=False).head(20))

# High cardinality columns
print("Columns with >95% unique:", [col for col in data1.columns if data1[col].nunique()/len(data1) > 0.95])

SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_         817
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_           817
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_        817
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_                   817
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_      817
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_                      817
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_        808
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____CATEGORY__INTEGER_FOR_VISUALS_     808
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_                  808
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_          808
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_                     808
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_       808
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_          801
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_                     801
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_        801
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____RAW_VALUE__MEDIAN_OF_5_GCMS_       801
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____SCORE__0_5_SCALE_                  801
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2035_2065_____CATEGORY__INTEGER_FOR_VISUALS_     801
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____RAW_VALUE__MEDIAN_OF_5_GCMS_    798
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2030__2015_2045_____SCORE__0_5_SCALE_            798
dtype: int64
Columns with >95% unique: ['FEATURE_ID', 'PFAFSTETTER_ID']

In [14]:
# Numeric columns
num_cols = data1.select_dtypes(include=['number']).columns
data1[num_cols] = data1[num_cols].fillna(data1[num_cols].median())
# Categorical/object columns
cat_cols = data1.select_dtypes(include='object').columns
for col in cat_cols:
    data1[col] = data1[col].fillna(data1[col].mode().iloc[0])

In [15]:
print(data1.isnull().sum().sum())  # Should return 0

0

In [16]:
print(f"Duplicate rows: {data1.duplicated().sum()}")

Duplicate rows: 0

In [18]:
print(data1.describe(include='all').T)

                                                      count unique  \
FEATURE_ID                                          16395.0    NaN
PFAFSTETTER_ID                                      16395.0    NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...    16395      8
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...    16395      8
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...    16395      8
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...  16395.0    NaN
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...    16395      8
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...  16395.0    NaN
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...    16395      8
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...  16395.0    NaN
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...    16395      8
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...  16395.0    NaN
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...    16395      8
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...  16395.0    NaN
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...    16395      8
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...  16395.0    NaN
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...    16395      8
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...  16395.0    NaN
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...    16395      5
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...  16395.0    NaN
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...    16395      5
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...  16395.0    NaN
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...    16395      5
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...  16395.0    NaN
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...    16395      5
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...  16395.0    NaN
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...    16395      5
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...  16395.0    NaN
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...    16395      5
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...  16395.0    NaN
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...    16395      5
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...  16395.0    NaN
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...    16395      5
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...  16395.0    NaN
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...    16395      5
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...    16395      6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...    16395      6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...  16395.0    NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...    16395      6
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...    16395      6
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...    16395      6
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...  16395.0    NaN
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...    16395      6
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...    16395      6
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...    16395      6
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...  16395.0    NaN
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...    16395      6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...    16395      6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...    16395      6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...  16395.0    NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...    16395      6
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...    16395      6
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...    16395      6
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...  16395.0    NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...    16395      6
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...    16395      6
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...    16395      6
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...  16395.0    NaN
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...    16395      6
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...    16395      6
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...    16395      6
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  16395.0    NaN
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...    16395      6
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...    16395      6
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...    16395      6
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...  16395.0    NaN
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...    16395      6
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...    16395      6
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...    16395      6
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...  16395.0    NaN
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...    16395      6
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...    16395      6
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...    16395      6
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  16395.0    NaN
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...    16395      6
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...    16395      6
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...    16395      6
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...  16395.0    NaN
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...    16395      6
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...    16395      6
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...    16395      6
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...  16395.0    NaN
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...    16395      6

                                                                         top  \
FEATURE_ID                                                               NaN
PFAFSTETTER_ID                                                           NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...                       NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...                 30-100 cm
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...                       NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...                 30-100 cm
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...                       NaN
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...                 30-100 cm
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...                       NaN
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...                 30-100 cm
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...                       NaN
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...                 30-100 cm
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...                       NaN
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...                 30-100 cm
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...                       NaN
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...                 30-100 cm
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...                       NaN
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...                 30-100 cm
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...                       NaN
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...                 30-100 cm
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...                       NaN
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...                    < 1 cm
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...                       NaN
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...                    < 1 cm
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...                       NaN
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...                    < 1 cm
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...                       NaN
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...                    < 1 cm
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...                       NaN
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...                    < 1 cm
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...                       NaN
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...                    < 1 cm
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...                       NaN
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...                    < 1 cm
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...                       NaN
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...                    < 1 cm
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...                       NaN
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...                    < 1 cm
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...                Low (<10%)
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...                Low (<10%)
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...                       NaN
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...                Low (<10%)
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...                Low (<10%)
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...                Low (<10%)
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...                       NaN
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...                Low (<10%)
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...                Low (<10%)
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...                Low (<10%)
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...                       NaN
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...                Low (<10%)
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...                 Low (<5%)
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...                 Low (<5%)
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...                       NaN
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...                 Low (<5%)
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...                 Low (<5%)
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...                 Low (<5%)
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...                       NaN
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...                 Low (<5%)
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...                       NaN

In [21]:
summary_tbl = pd.DataFrame({
    'dtype': data1.dtypes,
    'missing': data1.isnull().sum(),
    'missing_frac': data1.isnull().mean(),
    'nunique': data1.nunique()
})

print(summary_tbl)

                                                      dtype  missing  \
FEATURE_ID                                            int64        0
PFAFSTETTER_ID                                        int64        0
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...   object        0
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...   object        0
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...   object        0
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...  float64        0
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...   object        0
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...  float64        0
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...   object        0
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...  float64        0
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...   object        0
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...  float64        0
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...   object        0
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...  float64        0
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...   object        0
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...  float64        0
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...   object        0
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...  float64        0
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...   object        0
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...  float64        0
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...   object        0
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...  float64        0
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...   object        0
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...  float64        0
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...   object        0
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...  float64        0
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...   object        0
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...  float64        0
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...   object        0
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...  float64        0
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...   object        0
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...  float64        0
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...   object        0
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...  float64        0
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...   object        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...   object        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...   object        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...  float64        0
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...   object        0
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...   object        0
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...   object        0
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...  float64        0
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...   object        0
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...   object        0
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...   object        0
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...  float64        0
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...   object        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...   object        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...   object        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...  float64        0
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...   object        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...   object        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...   object        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...  float64        0
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...   object        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2030__2015_2...   object        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2050__2035_2...   object        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...  float64        0
WATER_DEPLETION__PESSIMISTIC__YEAR_2080__2065_2...   object        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...   object        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...   object        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...  float64        0
INTERANNUAL_VARIABILITY__BUSINESS_AS_USUAL__YEA...   object        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2030_...   object        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2050_...   object        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...  float64        0
INTERANNUAL_VARIABILITY__OPTIMISTIC__YEAR_2080_...   object        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2030...   object        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2050...   object        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...  float64        0
INTERANNUAL_VARIABILITY__PESSIMISTIC__YEAR_2080...   object        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...   object        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...   object        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...  float64        0
SEASONAL_VARIABILITY__BUSINESS_AS_USUAL__YEAR_2...   object        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2030__20...   object        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2050__20...   object        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...  float64        0
SEASONAL_VARIABILITY__OPTIMISTIC__YEAR_2080__20...   object        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2030__2...   object        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2050__2...   object        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...  float64        0
SEASONAL_VARIABILITY__PESSIMISTIC__YEAR_2080__2...   object        0

                                                    missing_frac  nunique
FEATURE_ID                                                   0.0    16395
PFAFSTETTER_ID                                               0.0    16395
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...           0.0    15404
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...           0.0        8
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...           0.0    15443
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...           0.0        8
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...           0.0    15477
BLUE_WATER_AVAILABILITY__BUSINESS_AS_USUAL__YEA...           0.0        8
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...           0.0    15377
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2030_...           0.0        8
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...           0.0    15417
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2050_...           0.0        8
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...           0.0    15461
BLUE_WATER_AVAILABILITY__OPTIMISTIC__YEAR_2080_...           0.0        8
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...           0.0    15392
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2030...           0.0        8
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...           0.0    15419
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2050...           0.0        8
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...           0.0    15464
BLUE_WATER_AVAILABILITY__PESSIMISTIC__YEAR_2080...           0.0        8
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...           0.0    15315
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2030__2015...           0.0        5
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...           0.0    15334
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2050__2035...           0.0        5
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...           0.0    15332
WITHDRAWALS__BUSINESS_AS_USUAL__YEAR_2080__2065...           0.0        5
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...           0.0    15309
WITHDRAWALS__OPTIMISTIC__YEAR_2030__2015_2045__...           0.0        5
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...           0.0    15333
WITHDRAWALS__OPTIMISTIC__YEAR_2050__2035_2065__...           0.0        5
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...           0.0    15334
WITHDRAWALS__OPTIMISTIC__YEAR_2080__2065_2095__...           0.0        5
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...           0.0    15319
WITHDRAWALS__PESSIMISTIC__YEAR_2030__2015_2045_...           0.0        5
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...           0.0    15326
WITHDRAWALS__PESSIMISTIC__YEAR_2050__2035_2065_...           0.0        5
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...           0.0    15332
WITHDRAWALS__PESSIMISTIC__YEAR_2080__2065_2095_...           0.0        5
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...           0.0    11597
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...           0.0     3794
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...           0.0        6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2030__201...           0.0        6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...           0.0    11657
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...           0.0     3939
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...           0.0        6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2050__203...           0.0        6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...           0.0    11767
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...           0.0     4089
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...           0.0        6
WATER_STRESS__BUSINESS_AS_USUAL__YEAR_2080__206...           0.0        6
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...           0.0    11506
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...           0.0     3712
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...           0.0        6
WATER_STRESS__OPTIMISTIC__YEAR_2030__2015_2045_...           0.0        6
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...           0.0    11685
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...           0.0     3879
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...           0.0        6
WATER_STRESS__OPTIMISTIC__YEAR_2050__2035_2065_...           0.0        6
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...           0.0    11617
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...           0.0     3888
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...           0.0        6
WATER_STRESS__OPTIMISTIC__YEAR_2080__2065_2095_...           0.0        6
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...           0.0    11508
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...           0.0     3777
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...           0.0        6
WATER_STRESS__PESSIMISTIC__YEAR_2030__2015_2045...           0.0        6
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...           0.0    11640
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...           0.0     3876
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...           0.0        6
WATER_STRESS__PESSIMISTIC__YEAR_2050__2035_2065...           0.0        6
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...           0.0    11777
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...           0.0     4069
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...           0.0        6
WATER_STRESS__PESSIMISTIC__YEAR_2080__2065_2095...           0.0        6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...           0.0    11332
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...           0.0    11834
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...           0.0        6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2030__...           0.0        6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...           0.0    11425
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...           0.0    11770
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...           0.0        6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2050__...           0.0        6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...           0.0    11495
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...           0.0    11720
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...           0.0        6
WATER_DEPLETION__BUSINESS_AS_USUAL__YEAR_2080__...           0.0        6
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...           0.0    11241
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...           0.0    11745
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...           0.0        6
WATER_DEPLETION__OPTIMISTIC__YEAR_2030__2015_20...           0.0        6
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...           0.0    11415
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...           0.0    11844
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...           0.0        6
WATER_DEPLETION__OPTIMISTIC__YEAR_2050__2035_20...           0.0        6
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...           0.0    11372
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...           0.0    11737
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...           0.0        6
WATER_DEPLETION__OPTIMISTIC__YEAR_2080__2065_20...           0.0        6

In [22]:
data1.to_csv('aqueduct_future_annual_cleaned.csv', index=False)